"""Mojo test to verify the Golden Round-trip from Rust.

This script reads 'golden_directive.bin' (generated by Rust) and verifies
that the Thai text and metadata are preserved correctly when parsed via
Mojo's Python-interop facade.
"""

from std.python import Python
from std.testing import assert_equal
from vtuber_contracts import ConversationDirective

def test_golden_roundtrip_from_rust() raises:
    # Use Python's open to read binary data
    var builtins = Python.import_module("builtins")
    var file = builtins.open("golden_directive.bin", "rb")
    var bytes = file.read()
    file.close()

    var decoded = ConversationDirective.parse(bytes)

    print("Checking Directive ID...")
    assert_equal(decoded.directive_id(), "test-golden-roundtrip-001")
    
    print("Checking Persona ID...")
    assert_equal(String(decoded.persona_id()), "1") # PersonaId.PERSONA_ID_VALORA

    print("Checking Thai Text Prompt...")
    # The exact string from Rust: "สวัสดี ยินดีที่ได้รู้จัก!"
    assert_equal(decoded.text_prompt(), "สวัสดี ยินดีที่ได้รู้จัก!")

    print("Checking Voice Prompt...")
    assert_equal(decoded.voice_prompt(), "thai-accent-test")

    print("Checking Emotion...")
    assert_equal(String(decoded.emotion()), "2") # Emotion.EMOTION_HAPPY

    print("Checking Audio Format...")
    assert_equal(String(decoded.target_audio_format()), "1") # AudioFormat.AUDIO_FORMAT_WAV

    print("Checking Max Latency...")
    assert_equal(String(decoded.max_latency_ms()), "500")

    print("Golden Round-trip Verification: SUCCESS")

def main() raises:
    test_golden_roundtrip_from_rust()
